### PR TITLE
:hammer: adjust-menu-position-on-mobile

### LINKED ISSUE #5: Navbar hidden behind the URL bar on mobile
The navbar is hidden behind the URL bar on mobiles -

image

It should be visible like this below the URL bar -

image

### PR DESCRIPTION
**Pull request by VasekS**
Feel free to test on http://responsivetesttool.com or your Xcode (if you have use Mac) :) Let me know if there is any feedback

### CODE REVIEW

**Review by iamyajat — CHANGES_REQUESTED** [review]
The issue still seems to exist :(
Try again, if not possible then just make the height of the inner container 80% of the total height

**Comment by VasekS** [comment]
Hey @iamyajat please can you let me know what device are you testing this on?

EDIT: Just submitted new [PR](https://github.com/iamyajat/retro-portfolio-website/pull/6/commits/eadbe6e5f828334eb9f92df3e656f0344d6f925d).

**Review by iamyajat — COMMENTED** [review]
Looks good to me

**Review by iamyajat — APPROVED** [review]
Looks good to me

**Comment by iamyajat** [comment]
> Hey @iamyajat please can you let me know what device are you testing this on?


I was testing it on Microsoft Edge on my Android phone

**Comment by iamyajat** [comment]
It looks good now! Thanks for contributing.
Happy open sourcing!

[Let's connect](https://linkinbio.iamyajat.co/)

**Pull request merged**
