### PR TITLE
Add responsive layout to website

### LINKED ISSUE #1: Make website responsive
Make the website responsive for various different screen sizes

### PR DESCRIPTION
**Pull request by griseduardo**
**Motivation**

Add responsive layout to website

**Solution**

- Adjust size and position of elements in lower width sizes
- Change menu to hamburger menu in lower width sizes

**Issue**
https://github.com/iamyajat/retro-portfolio-website/issues/1

Closed Menu:

Screenshot 2021-10-23 at 18-15-04 Yajat Malhotra

Opened Menu:

Screenshot 2021-10-23 at 18-15-21 Yajat Malhotra

### CODE REVIEW

**Review by iamyajat — CHANGES_REQUESTED** [review]
The component that shows up after clicking the `Explore` button can be made to take the whole screen width and height on smaller screen devices like mobiles.

Cuz of that blue padding around the component, the actual viewable area becomes very less.

image

@erikvega

**Comment by griseduardo** [comment]
I updated here to increase view area in mobile

**Review by iamyajat — CHANGES_REQUESTED** [review]
@erikvega,

Just one small thing; Scale the inner contents also.
The rest looks perfect!


Update this: 

image

to something like this

Screenshot 2021-10-23 at 18-15-04 Yajat Malhotra

**Review by iamyajat — APPROVED** [review]
Looks good to me

**Comment by iamyajat** [comment]
Good job @griseduardo! 
Happy open-sourcing!!

[Let's Connect!](https://linkinbio.iamyajat.co/)

**Pull request merged**
