### PR TITLE
updated readme and added screenshots for readme

### LINKED ISSUE #2: Improve the readme
The following needs to be done:
1. Change title
2. Add a link to the website
3. Add some screenshots
4. Add instructions to run locally

### PR DESCRIPTION
**Pull request by erikvegax**
Closes #2

### CODE REVIEW

**Comment by erikvegax** [comment]
maybe download this on your local and see if you can see the images in the readme. never added screenshots to a readme so this is a first

**Review by iamyajat — APPROVED** [review]
Looks good to me

**Comment by iamyajat** [comment]
Great job @erikvega! 
Happy open-sourcing!!

[Let's connect!](https://linkinbio.iamyajat.co)

**Comment by erikvegax** [comment]
thank you :)

**Pull request merged**
